version: '3'
services:
  cars_api:
    build:
      context: '.'
      dockerfile: './Dockerfile'
    ports:
    - "8000:8000"
    command: python -m uvicorn cars_api.main:app --reload --host 0.0.0.0
