version: '3'
services:
  cars_api:
    build:
      context: '.'
      dockerfile: './Dockerfile'
    ports:
    - "8000:8000"
    command: >
      sh -c "python -m scripts.init_db && python -m uvicorn cars_api.main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
    - ./db:/srv/db